folder:
  images: ${USER_IMAGES_PATH:../User_Images/}
  defaultImage: default-visitor.png

spring:
  config:
    import: optional:classpath:secret-application.yml

  datasource:
    url: jdbc:sqlite:${SQLITE_DB_PATH:visitor-entry.db}
    driver-class-name: org.sqlite.JDBC
    hikari:
      connection-init-sql: PRAGMA foreign_keys=ON

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  graphql:
    path: /graphql

    websocket:
      path: /graphql

    graphiql:
      enabled: true
      path: /graphiql

    cors:
      allow-credentials: true
      allowed-origins:
        - http://localhost:3000
        - http://localhost:5173
        - http://192.168.0.191:3000
      allowed-methods:
        - GET
        - POST
        - OPTIONS
      allowed-headers:
        - "*"

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB

  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  shutdown: graceful

logging:
  level:
    org.flywaydb: INFO
    org.hibernate.SQL: WARN
    org.springframework: INFO

expiration_time: 30
